export const ingredients = [
    {id: "", title: "Coke"},
    {id: "", title: "Rum"},
    {id: "", title:"Vodka"},
    {id: "", title:'Gin'},
    {id: "", title:'Tonic'},
    {id: "", title:'Irish Cream'},
    {id: "", title:'Sprite'},
    {id: "", title:'Orange Liqueur'},
    {id: "", title:'Lemon Juice'},
    {id: "", title:'Lime Juice'},
    {id: "", title:'Tequila'},
    {id: "", title:'Simple Syrup'},
    {id: "", title:'Sweet Vermouth'},
    {id: "", title:'Dry Vermouth'},
    {id: "", title:'Lilic Blanc'},
    {id: "", title:'Campari'},
    {id: "", title:'Sour'},
    {id: "", title:'Whiskey'},
    {id: "", title:'Orange Juice'},
    {id: "", title:'Club Soda'},
    {id: "", title:'Coffee Liqueur'},
    {id: "", title:'Espresso Coffee'},
    {id: "", title:'Bitters'},
    {id: "", title:'Bourbon'},
    {id: "", title:'Amaretto'},
    {id: "", title:'Mint Leaves'},
    {id: "", title:'Brandy'},
    {id: "", title:'Cranberry Juice'},
    {id: "", title:'Champagne'},
    {id: "", title:'Coconut Milk'},
    {id: "", title:'Grenadine'},
    {id: "", title:'Absinthe'},
    {id: "", title:'Cherry Liqueur'},
    {id: "", title:'Benedictine'},
    {id: "", title:'Pineapple Juice'},
    {id: "", title:'Cachaça'},
    {id: "", title:'Ginger Beer'},
    {id: "", title:'Blue Curacao'},
    {id: "", title:'Lemonade'},
    {id: "", title:'Peach Schnapps'},
    {id: "", title:'Egg White'},
    {id: "", title:'Pisco'},
    {id: "", title:'Aperol'},
    {id: "", title:'Prosecco'},
    {id: "", title:'Grapefruit Juice'},
    {id: "", title:'Raspberry Liqueur'},
    {id: "", title:'Orgeat Syrup'},
    {id: "", title:'Chocolate Liqueur'},
    {id: "", title:'Cream'},
    {id: "", title:'Apple Liqueur'},
    {id: "", title:'Coconut Rum'},
    {id: "", title:'Milk'},
    {id: "", title:'Apple Brandy'},
    {id: "", title:'Green Chartreuse'},
    {id: "", title:'Violette Liqueur'}
]

for (let i = 0; i < ingredients.length; i++) {
    ingredients[i].id = i;
}